server:
  port: 8090

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5431}/${DB_NAME:product-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
